In [1]:
import pandas as pd

In [14]:
# data = pd.read_excel("RTV_control_2023_Year2_Combined_Outlier_Managed_Aggregated.xlsx",header=5)
data = pd.read_excel("RTV_control_2023_Year2_Combined_Outlier_Managed_Aggregated.xlsx",header=5)

KeyboardInterrupt:

In [4]:
data.head()

,SubmissionDate,starttime,endtime,version,duration,deviceid,deviceinfo,survey_start,intro_start,text_audit,...,Pineapple,Mandarin (mangada),Teak tree,Shea tree,Edible Bamboo (Malewa),Paw paw,Cinnamon,Macadamia,Others.1,Perennials Grown
0,"Aug 16, 2025 5:49:40 PM","Aug 16, 2025 3:20:49 PM","Aug 16, 2025 4:10:11 PM",2508151101,2961,538e295a1675b326,samsung|SM-X115|14|SurveyCTO Collect 2.81.4 (4...,6.0,6.0,https://rtvuganda.surveycto.com/view/submissio...,...,0,0,0,0,0,0,0,0,0,0
1,"Aug 19, 2025 5:43:30 PM","Aug 19, 2025 1:42:02 PM","Aug 19, 2025 2:29:17 PM",2508151101,2833,c747318886b4bf02,samsung|SM-X115|14|SurveyCTO Collect 2.81.4 (4...,2.0,2.0,https://rtvuganda.surveycto.com/view/submissio...,...,0,0,0,0,0,0,0,0,0,2
2,"Aug 19, 2025 5:56:56 PM","Aug 19, 2025 3:46:44 PM","Aug 19, 2025 4:56:29 PM",2508151101,2475,db89cae1d4855558,samsung|SM-T225N|14|SurveyCTO Collect 2.81.4 (...,18.0,18.0,https://rtvuganda.surveycto.com/view/submissio...,...,0,0,0,0,0,0,0,0,0,0
3,"Aug 20, 2025 7:52:36 PM","Aug 20, 2025 1:53:13 PM","Aug 20, 2025 3:07:52 PM",2508200304,3841,58f1cb727c848422,samsung|SM-T225N|13|SurveyCTO Collect 2.81.4 (...,6.0,6.0,https://rtvuganda.surveycto.com/view/submissio...,...,0,0,0,0,0,0,0,0,0,1
4,"Aug 20, 2025 6:19:29 AM","Aug 19, 2025 12:53:50 PM","Aug 19, 2025 1:32:45 PM",2508151101,2247,b9b1347fae7fa345,samsung|SM-X115|14|SurveyCTO Collect 2.81.4 (4...,1.0,1.0,https://rtvuganda.surveycto.com/view/submissio...,...,0,0,0,0,0,0,0,0,0,2

In [5]:
df = data.copy()

In [5]:
# df.to_csv("Combined_2024_merged.csv", index=False)

In [7]:
# df['pre_cohort'].value_counts()

In [8]:
# year_2 = df[df['pre_cohort'] == 2022]
# year_5 = df[df['pre_cohort'] == 2019]

In [9]:
df['treat_status'].value_counts()

treat_status
Treatment    12404
Control       3070
Name: count, dtype: int64

## Expenditure

"consumption_exp_weekly(ugx)"	"consumption_exp_monthly"	"consumption_exp _annual"

In [13]:
df["consumption_weekly(ugx)"].mean()

2127915.7813105853

In [11]:
df.groupby('treat_status')["consumption_weekly(ugx)"].mean() / 3700

treat_status
Control      406.929624
Treatment    616.737739
Name: consumption_weekly(ugx), dtype: float64

In [12]:
df.groupby('consumption_weekly(ugx)')["consumption_exp_monthly"].mean() / 3700

KeyError: 'Column not found: consumption_exp_monthly'

In [13]:
year_5.groupby('STATUS')["consumption_exp_monthly"].mean() / 3700

STATUS
RTV    120.77607
Name: consumption_exp_monthly, dtype: float64

In [14]:
year_2.groupby('STATUS')["consumption_exp _annual"].mean() / 3700

STATUS
PEER    68.182653
RTV     81.692755
Name: consumption_exp _annual, dtype: float64

In [15]:
year_5.groupby('STATUS')["consumption_exp _annual"].mean() / 3700

STATUS
RTV    75.570647
Name: consumption_exp _annual, dtype: float64

In [16]:
year_2.groupby(['pre_district','STATUS'])["consumption_exp_weekly(ugx)"].mean() / 3700

pre_district     STATUS
Kagadi_GAC       RTV       544.912548
Kagadi_Standard  RTV       574.826415
Kaliro           PEER      341.027601
                 RTV       349.874716
Kanungu          PEER      384.729291
                 RTV       564.982422
Kibaale          PEER      443.588743
Kyenjojo         RTV       538.464323
Mitooma          PEER      423.984836
                 RTV       514.306650
Rubanda          PEER      285.773774
                 RTV       305.211432
Rubirizi         RTV       510.519247
Rukungiri        RTV       526.288512
kanungu          PEER      157.405405
Name: consumption_exp_weekly(ugx), dtype: float64

In [17]:
year_5.groupby(['pre_district','STATUS'])["consumption_exp_weekly(ugx)"].mean() / 3700

pre_district  STATUS
Kanungu       RTV       470.143645
Kisoro        RTV       395.169039
Rukungiri     RTV       465.729844
kanungu       RTV        94.054054
Name: consumption_exp_weekly(ugx), dtype: float64

In [18]:
year_2.groupby(['pre_district','STATUS'])["consumption_exp_monthly"].mean() / 3700

pre_district     STATUS
Kagadi_GAC       RTV       125.892342
Kagadi_Standard  RTV       123.793214
Kaliro           PEER      109.215129
                 RTV       122.641606
Kanungu          PEER       92.294884
                 RTV       123.734735
Kibaale          PEER      129.199822
Kyenjojo         RTV       156.361785
Mitooma          PEER      114.993954
                 RTV       128.038960
Rubanda          PEER       87.582583
                 RTV       105.961205
Rubirizi         RTV       128.100067
Rukungiri        RTV       154.779517
kanungu          PEER      140.540541
Name: consumption_exp_monthly, dtype: float64

In [19]:
year_5.groupby(['pre_district','STATUS'])["consumption_exp_monthly"].mean() / 3700

pre_district  STATUS
Kanungu       RTV       112.576894
Kisoro        RTV        74.646410
Rukungiri     RTV       144.336124
kanungu       RTV        28.648649
Name: consumption_exp_monthly, dtype: float64

In [20]:
year_2.groupby(['pre_district','STATUS'])["consumption_exp _annual"].mean() / 3700

pre_district     STATUS
Kagadi_GAC       RTV       100.555201
Kagadi_Standard  RTV       106.360787
Kaliro           PEER       60.245637
                 RTV        65.344184
Kanungu          PEER       58.157420
                 RTV        73.993968
Kibaale          PEER       94.203167
Kyenjojo         RTV       101.777603
Mitooma          PEER       75.091999
                 RTV        84.840418
Rubanda          PEER       50.573991
                 RTV        61.501210
Rubirizi         RTV        76.775000
Rukungiri        RTV        89.402986
kanungu          PEER       98.648649
Name: consumption_exp _annual, dtype: float64

In [21]:
year_5.groupby(['pre_district','STATUS'])["consumption_exp _annual"].mean() / 3700

pre_district  STATUS
Kanungu       RTV       71.047826
Kisoro        RTV       55.904526
Rukungiri     RTV       87.603241
kanungu       RTV        7.612613
Name: consumption_exp _annual, dtype: float64

# Expenses

In [23]:
year_2.groupby(['pre_district','STATUS'])["Total Expenses"].mean() / 3700

pre_district     STATUS
Kagadi_GAC       RTV       1209.992736
Kagadi_Standard  RTV       1237.236901
Kaliro           PEER       805.076267
                 RTV       1077.494841
Kanungu          PEER       866.203147
                 RTV       1269.321398
Kibaale          PEER      1182.983800
Kyenjojo         RTV       1209.566490
Mitooma          PEER      1063.904405
                 RTV       1232.351728
Rubanda          PEER       748.567854
                 RTV       1025.499359
Rubirizi         RTV       1270.318830
Rukungiri        RTV       1267.742680
kanungu          PEER       652.101351
Name: Total Expenses, dtype: float64

In [24]:
year_5.groupby(['pre_district','STATUS'])["Total Expenses"].mean() / 3700

pre_district  STATUS
Kanungu       RTV       1167.736044
Kisoro        RTV        927.061890
Rukungiri     RTV       1274.389758
kanungu       RTV        495.162162
Name: Total Expenses, dtype: float64

In [22]:
df['Total Expenses'].mean()

4193947.4030117043

In [32]:
year_2['pre_district'] == "Kibaale"

0        False
1        False
2        False
3        False
4        False
         ...
11337    False
11338    False
11339    False
11340    False
11341    False
Name: pre_district, Length: 11342, dtype: bool

In [30]:
year_2['

,SubmissionDate,starttime,endtime,version,duration,survey_start,intro_start,text_audit,date_collection,region,...,Beetroot,Black nightshade,White eggplants,Green Eggplants,Purple Eggplants,Dodo (Amaranthus),Others.1,Vegs_Num,Unnamed: 7218,STATUS
0,"Jul 29, 2024 11:16:27 PM","Jul 29, 2024 5:25:05 PM","Jul 29, 2024 6:06:27 PM",2407300828,2457,4.0,4.0,https://rtvuganda.surveycto.com/view/submissio...,45503,4,...,0,0,0,0,0,0,0,0,NaN,PEER
1,"Jul 29, 2024 2:20:16 PM","Jul 29, 2024 1:20:26 PM","Jul 29, 2024 2:19:54 PM",2407301247,3291,9.0,9.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-30,4,...,0,0,0,0,0,0,0,0,NaN,PEER
2,"Jul 29, 2024 11:18:08 AM","Jul 29, 2024 10:23:17 AM","Jul 29, 2024 11:17:39 AM",2407300924,3261,4.0,4.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-30,4,...,0,0,0,0,0,0,0,0,NaN,PEER
3,"Jul 29, 2024 6:15:33 PM","Jul 29, 2024 1:44:04 PM","Jul 29, 2024 2:30:23 PM",2407301035,2592,38.0,38.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-30,4,...,0,0,0,0,0,0,0,0,NaN,PEER
4,"Jul 29, 2024 5:54:45 PM","Jul 29, 2024 3:13:19 PM","Jul 29, 2024 4:04:00 PM",2407301135,2912,27.0,27.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-30,4,...,0,0,0,0,0,0,0,0,NaN,PEER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11337,"Jul 31, 2024 3:26:03 AM","Jul 30, 2024 11:01:51 AM","Jul 30, 2024 11:58:08 AM",2407302157,3368,4.0,4.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-31,4,...,0,0,0,0,0,1,0,1,NaN,RTV
11338,"Jul 31, 2024 9:27:47 PM","Jul 31, 2024 10:13:18 AM","Jul 31, 2024 11:35:34 AM",2407311236,4936,2.0,2.0,https://rtvuganda.surveycto.com/view/submissio...,2024-08-01,4,...,0,0,1,0,0,1,0,2,NaN,RTV
11339,"Jul 30, 2024 7:33:52 PM","Jul 30, 2024 12:27:26 PM","Jul 30, 2024 2:24:14 PM",2407302157,10844,3.0,3.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-31,4,...,0,0,0,0,0,1,0,2,NaN,RTV
11340,"Jul 31, 2024 6:17:41 PM","Jul 31, 2024 9:30:01 AM","Jul 31, 2024 10:37:15 AM",2407311236,3578,45.0,45.0,https://rtvuganda.surveycto.com/view/submissio...,2024-08-01,4,...,0,0,1,0,0,1,0,2,NaN,RTV
11341,"Jul 29, 2024 9:42:41 PM","Jul 29, 2024 12:59:06 PM","Jul 29, 2024 2:05:44 PM",2407300828,3193,35.0,35.0,https://rtvuganda.surveycto.com/view/submissio...,2024-07-30,4,...,0,0,1,0,0,1,0,4,NaN,RTV